{{- if .Values.htcMaster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccb-pod
  labels:
    app.kubernetes.io/name: htc-master-pod
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: htc-master
    spec:
      priorityClassName: system-node-critical
      affinity:
{{- if .Values.htcMaster.nodeSelector }}
{{ .Values.htcMaster.nodeSelector | indent 8 }}
{{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - htc-master 
            topologyKey: kubernetes.io/hostname 
      hostNetwork: true
      {{- if .Values.ttsCache.enabled }}
      serviceAccountName: tts-account
      {{- end }}
      containers:
      {{- if .Values.ttsCache.enabled }}
      - name: tts
        imagePullPolicy: "{{ .Values.ttsCache.pullPolicy }}"
        image: "{{ .Values.ttsCache.image }}:{{ .Values.ttsCache.tag }}"
        args:
          - --get-proxy
          - --period
          - "120"
          - "--config"
          - "/app/.config.yaml"
        resources:
          limits:
            memory: "500M"
            cpu: "100m"
        volumeMounts:
          - name: proxydir
            mountPath: /root/proxy
      {{- end }}
      - name: ccb
        imagePullPolicy: {{ .Values.htcMaster.pullPolicy }}
        args:
        - master 
        env:
        - name: NETWORK_INTERFACE
          value:   "{{ .Values.htcMaster.networkInterface }}"          
        - name: CONDOR_HOST 
          value:   "{{ .Values.condorHost  }}"
        - name: PROXY_CACHE 
          value: "{{ .Values.proxyCacheHost }}:{{ .Values.proxyCachePort }}"
        - name: SEC_DAEMON_AUTHENTICATION_METHODS
          value: CLAIMTOBE
        - name: SEC_CLIENT_AUTHENTICATION_METHODS
          value: CLAIMTOBE
        - name: SEC_NEGOTIATOR_AUTHENTICATION_METHODS
          value: CLAIMTOBE
        - name: SEC_ADVERTISE_STARTD_AUTHENTICATION_METHODS
          value: CLAIMTOBE
        - name: CONDOR_DAEMON_LIST
          value: COLLECTOR, MASTER, NEGOTIATOR, SCHEDD, STARTD

        image: "{{ .Values.htcMaster.image }}:{{ .Values.htcMaster.tag }}"
        livenessProbe:
          exec:
            command:
            - voms-proxy-info
            - --file
            - /root/proxy/gwms_proxy
            - --exists
            - --valid
            - "6:00"
          initialDelaySeconds: 300
          periodSeconds: 600
        volumeMounts: 
          - mountPath: "/etc/condor/config.d"
            name: configd
{{- if .Values.ttsCache.enabled }}
          - name: proxydir
            mountPath: /root/proxy
{{- end }}
      volumes:
      - name: configd
        configMap:
          name: ccbconfigd
{{- if .Values.ttsCache.enabled }}
      - name: proxydir
        emptyDir: {}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: htc-master

  replicas: {{ .Values.htcMaster.replicas }}
{{- end }}