{{- if .Values.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-pod
  labels:
    app.kubernetes.io/name: proxy
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy
    spec:
      {{- if .Values.gsi.enabled }}
      volumes:
      - name: xcache-creds
        emptyDir: {}
      {{- if .Values.gsi.vo }}
      - name: vomses
        configMap:
          name: vomses-config
      {{- end }}
      - name: certs
        secret:
          secretName: certs
          defaultMode: 256
      {{- end }}
      containers:
      - name: proxy
        imagePullPolicy: {{  .Values.proxy.pullPolicy }}
        args:
        {{- if not .Values.gsi.enabled }}
        - --nogsi
        {{- end }}
        {{- if not .Values.gsi.proxy }}
        - --nogrid
        {{- end }}
        - --expose
        - --health_port
        - "8080"
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/check_health
          initialDelaySeconds: 300
          periodSeconds: 60
        env:
        - name: REDIR_HOST
          value: "{{ .Values.cache.redirHost }}"
        - name: REDIR_XRD_PORT
          value: "{{ .Values.redirector.service.xrootd.port }}"
        image: "{{ .Values.proxy.image }}:{{ .Values.proxy.tag }}"
        {{- if .Values.gsi.enabled }} 
        volumeMounts:
        - name: certs
          mountPath: "/etc/grid-security/xrd/cert"
          readOnly: true
        - mountPath: /tmp/
          name: xcache-creds
        {{- end }}

      {{- if .Values.gsi.enabled }}
      ## WAITING FOR VOMS TTS solution
      - name: renew
        imagePullPolicy: {{  .Values.proxy.pullPolicy }}
        args:
          - --renew
          {{- if .Values.gsi.vo }}
          - --vo 
          - "{{ .Values.gsi.vo }}"
          {{- end}}
        image: "{{ .Values.cache.repository }}:{{ .Values.cache.tag }}"
        volumeMounts:
        - name: xcache-creds
          mountPath: /tmp/
        {{- if .Values.gsi.vo }}
        - name: vomses
          mountPath: /etc/vomses
        {{- end }}
        - name: certs
          mountPath: "/etc/grid-security/xrd/cert"
          readOnly: true
        livenessProbe:
          exec:
            command:
            - sudo
            - -u
            - xrootd
            - voms-proxy-info
          initialDelaySeconds: 300
          periodSeconds: 600
      {{- end }}  
{{- end }}